apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-service
  namespace: web-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer-service
  template:
    metadata:
        labels:
          app: tripviewer-service
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: poi
        image: registryzjk6277.azurecr.io/tripinsights/tripviewer:1.0
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile:80"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips-service:80"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
spec:
  ports:
  - port: 80
  selector:
    app: tripviewer-service
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tripviewer-ingress
  annotations:
   kubernetes.io/ingress.class: "nginx"
spec:
   rules:
   - http:
      paths:
      - path: /
        backend:
         serviceName: tripviewer-service
         servicePort: 80
