apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer-service
  template:
 
  metadata:
      labels:
        app: tripviewer-service
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: poi
        image: registryzjk6277.azurecr.io/tripinsights/tripviewer:1.0
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8288
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
spec:
  ports:
  - port: 8288
  selector:
    app: tripviewer-service
